# Create pod with dobby application docker image and expose port 4444
apiVersion: v1
kind: Pod
metadata:
  name: dobby
  labels:
    app: dobby
spec:
  containers:
    - name: dobby
      image: thecasualcoder/dobby
      ports:
        - containerPort: 4444
      env:
        - name: VERSION
          value: "0.0.1"