## Create POD description yaml for metadata service
apiVersion: v1
kind: Pod
metadata:
  name: metadata
  labels:
    app: metadata
spec:
  containers:
    - name: metadata
      image: sunitparekh/metadata:v1.0
      ports:
          - containerPort: 8080