apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-service
  labels:
    tier: metadata-service
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: metadata-service
  template:
    metadata:
      labels:
        tier: metadata-service
    spec:
      containers:
        - name: metadata-replicaset
          image: luckyganesh/metadata-service:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
