# Create pod with dobby application docker image and expose port 4444
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby-deployment
  labels:
    tier: dobby-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobby-pod
  template:
    metadata:
      labels:
        app: dobby-pod
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
