apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    tier: metadata-service
